# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  database: evite_mysql_development
  pool: 10
  username: root
  password: 34151119
  socket: /tmp/mysql.sock 
  host: localhost
  # When two programs want to talk to each other over the network, 
  # one program might open up a TCP connection (a "socket") with the other one. 
  # The first program needs to know the IP address of the second computer 
  # and the port on which the program is listening.
  
  # On Linux, when two programs on the same computer want to talk to each other, 
  # they can still open up a TCP connection. 
  # But they can also open up a connection via a "socket file". 
  # Linux makes the socket file API rather similar to the TCP API, 
  # so it's not a big deal to update a program that already communicates 
  # over the network via TCP to support communicating via socket files too. 
  # Socket files are faster than TCP, but only work when both programs are on the same computer.

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  database: evite_mysql_test
  pool: 10
  username: root
  password: 34151119
  socket: /tmp/mysql.sock
  host: localhost

## production: 